/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as LegalWiderrufRouteImport } from './routes/legal.widerruf'
import { Route as LegalVersandRouteImport } from './routes/legal.versand'
import { Route as LegalImpressumRouteImport } from './routes/legal.impressum'
import { Route as LegalDatenschutzRouteImport } from './routes/legal.datenschutz'
import { Route as LegalAgbRouteImport } from './routes/legal.agb'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalWiderrufRoute = LegalWiderrufRouteImport.update({
  id: '/widerruf',
  path: '/widerruf',
  getParentRoute: () => LegalRoute,
} as any)
const LegalVersandRoute = LegalVersandRouteImport.update({
  id: '/versand',
  path: '/versand',
  getParentRoute: () => LegalRoute,
} as any)
const LegalImpressumRoute = LegalImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => LegalRoute,
} as any)
const LegalDatenschutzRoute = LegalDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => LegalRoute,
} as any)
const LegalAgbRoute = LegalAgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => LegalRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/legal': typeof LegalRouteWithChildren
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/legal/agb': typeof LegalAgbRoute
  '/legal/datenschutz': typeof LegalDatenschutzRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/versand': typeof LegalVersandRoute
  '/legal/widerruf': typeof LegalWiderrufRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/legal': typeof LegalRouteWithChildren
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/legal/agb': typeof LegalAgbRoute
  '/legal/datenschutz': typeof LegalDatenschutzRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/versand': typeof LegalVersandRoute
  '/legal/widerruf': typeof LegalWiderrufRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/legal': typeof LegalRouteWithChildren
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/legal/agb': typeof LegalAgbRoute
  '/legal/datenschutz': typeof LegalDatenschutzRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/versand': typeof LegalVersandRoute
  '/legal/widerruf': typeof LegalWiderrufRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/legal'
    | '/shop'
    | '/sitemap.xml'
    | '/admin/orders'
    | '/checkout/return'
    | '/legal/agb'
    | '/legal/datenschutz'
    | '/legal/impressum'
    | '/legal/versand'
    | '/legal/widerruf'
    | '/order/$id'
    | '/product/$id'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/legal'
    | '/shop'
    | '/sitemap.xml'
    | '/admin/orders'
    | '/checkout/return'
    | '/legal/agb'
    | '/legal/datenschutz'
    | '/legal/impressum'
    | '/legal/versand'
    | '/legal/widerruf'
    | '/order/$id'
    | '/product/$id'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/legal'
    | '/shop'
    | '/sitemap.xml'
    | '/admin/orders'
    | '/checkout/return'
    | '/legal/agb'
    | '/legal/datenschutz'
    | '/legal/impressum'
    | '/legal/versand'
    | '/legal/widerruf'
    | '/order/$id'
    | '/product/$id'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  LegalRoute: typeof LegalRouteWithChildren
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/widerruf': {
      id: '/legal/widerruf'
      path: '/widerruf'
      fullPath: '/legal/widerruf'
      preLoaderRoute: typeof LegalWiderrufRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/versand': {
      id: '/legal/versand'
      path: '/versand'
      fullPath: '/legal/versand'
      preLoaderRoute: typeof LegalVersandRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/impressum': {
      id: '/legal/impressum'
      path: '/impressum'
      fullPath: '/legal/impressum'
      preLoaderRoute: typeof LegalImpressumRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/datenschutz': {
      id: '/legal/datenschutz'
      path: '/datenschutz'
      fullPath: '/legal/datenschutz'
      preLoaderRoute: typeof LegalDatenschutzRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/agb': {
      id: '/legal/agb'
      path: '/agb'
      fullPath: '/legal/agb'
      preLoaderRoute: typeof LegalAgbRouteImport
      parentRoute: typeof LegalRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LegalRouteChildren {
  LegalAgbRoute: typeof LegalAgbRoute
  LegalDatenschutzRoute: typeof LegalDatenschutzRoute
  LegalImpressumRoute: typeof LegalImpressumRoute
  LegalVersandRoute: typeof LegalVersandRoute
  LegalWiderrufRoute: typeof LegalWiderrufRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalAgbRoute: LegalAgbRoute,
  LegalDatenschutzRoute: LegalDatenschutzRoute,
  LegalImpressumRoute: LegalImpressumRoute,
  LegalVersandRoute: LegalVersandRoute,
  LegalWiderrufRoute: LegalWiderrufRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  LegalRoute: LegalRouteWithChildren,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  OrderIdRoute: OrderIdRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
