// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  // apikey/Authorization header'ları yalnızca ISO-8859-1 karakter kabul eder;
  // ortam değişkeninde görünmez bir karakter (kopyala-yapıştır kaynaklı, ör.
  // akıllı tırnak/sıfır genişlikli boşluk) varsa tarayıcı fetch'i "String
  // contains non ISO-8859-1 code point" hatasıyla tamamen çöker — giriş/kayıt
  // formları dahil HİÇBİR şey çalışmaz. Sadece uyarmak yetmiyor: değeri
  // gerçekten temizleyip en azından anlaşılır bir 401/geçersiz anahtar
  // hatasına düşmesini sağlıyoruz.
  const stripBad = (v: string, name: string) => {
    const cleaned = v.replace(/[^\x00-\xFF]/g, '');
    if (cleaned !== v) {
      console.error(
        `[Supabase] ${name} geçersiz karakter(ler) içeriyordu ve temizlendi. ` +
        `GitHub repo secrets'taki değeri silip yeniden, boşluksuz/görünmez karaktersiz yapıştırın.`
      );
    }
    return cleaned;
  };

  const SUPABASE_URL = stripBad((import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || '').trim(), 'VITE_SUPABASE_URL');
  const SUPABASE_PUBLISHABLE_KEY = stripBad((import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || '').trim(), 'VITE_SUPABASE_PUBLISHABLE_KEY');

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    // Uygulamayı çökertme: sayfa yine de render edilsin, auth çağrıları
    // ağ hatasıyla yakalanır ve kullanıcıya Türkçe hata mesajı gösterilir.
    console.error(
      `[Supabase] Eksik ortam değişken(ler)i: ${missing.join(', ')}. Giriş/sepet işlemleri çalışmayabilir.`
    );
    return createClient<Database>(
      SUPABASE_URL || 'https://placeholder.supabase.co',
      SUPABASE_PUBLISHABLE_KEY || 'public-anon-key-placeholder',
      {
        auth: {
          storage: typeof window !== 'undefined' ? localStorage : undefined,
          persistSession: true,
          autoRefreshToken: true,
        },
      }
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

