// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || '').trim();
  const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || '').trim();

  // apikey/Authorization header'ları yalnızca ISO-8859-1 karakter kabul eder;
  // ortam değişkeninde görünmez bir karakter (kopyala-yapıştır kaynaklı) varsa
  // tarayıcı fetch'i "String contains non ISO-8859-1 code point" hatasıyla
  // tamamen çöker (giriş/kayıt formları dahil). Erken ve anlaşılır uyar.
  if (SUPABASE_PUBLISHABLE_KEY && /[^\x00-\xFF]/.test(SUPABASE_PUBLISHABLE_KEY)) {
    console.error(
      '[Supabase] VITE_SUPABASE_PUBLISHABLE_KEY geçersiz karakter(ler) içeriyor. ' +
      'GitHub repo secrets\'taki değeri silip yeniden, boşluksuz olarak yapıştırın.'
    );
  }
  if (SUPABASE_URL && /[^\x00-\xFF]/.test(SUPABASE_URL)) {
    console.error(
      '[Supabase] VITE_SUPABASE_URL geçersiz karakter(ler) içeriyor. ' +
      'GitHub repo secrets\'taki değeri silip yeniden, boşluksuz olarak yapıştırın.'
    );
  }

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    // Uygulamayı çökertme: sayfa yine de render edilsin, auth çağrıları
    // ağ hatasıyla yakalanır ve kullanıcıya Türkçe hata mesajı gösterilir.
    console.error(
      `[Supabase] Eksik ortam değişken(ler)i: ${missing.join(', ')}. Giriş/sepet işlemleri çalışmayabilir.`
    );
    return createClient<Database>(
      SUPABASE_URL || 'https://placeholder.supabase.co',
      SUPABASE_PUBLISHABLE_KEY || 'public-anon-key-placeholder',
      {
        auth: {
          storage: typeof window !== 'undefined' ? localStorage : undefined,
          persistSession: true,
          autoRefreshToken: true,
        },
      }
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

